apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployment.name }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.deployment.name }}"
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
